### ISSUE TITLE
add --net command

### ISSUE THREAD

**Issue by wallnerryan** [j-bennet/wharfee#114]

**Comment by j-bennet** [comment]
You mean `docker run --net=XXX`?

**Comment by wallnerryan** [comment]
Yes, didn't seem to be there 

-Ryan

**Comment by j-bennet** [comment]
Yep, it's not. I'll add that.

**Comment by j-bennet** [comment]
@wallnerryan This is now in master (not on pypi yet).

**Comment by wallnerryan** [comment]
Thanks!


On Wed, Sep 16, 2015 at 3:08 PM, Iryna Cherniavska <notifications@github.com
> wrote:

> @wallnerryan <https://github.com/wallnerryan> This is now in master (not
> on pypi yet).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j-bennet/wharfee/issues/114#issuecomment-140846989>.
>



-- 

*-Ryan Wallner*

**Comment by wallnerryan** [comment]
@j-bennet FYI, tested ```--net [bridge | container: | none | host ]``` and seem to work as expected. thanks.

**Comment by j-bennet** [comment]
Great, thank you! Closing the issue.
