### ISSUE TITLE
Click shows warning about unicode_literals

### ISSUE THREAD

**Issue by j-bennet** [j-bennet/wharfee#124]
Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.command()

**Comment by kevinastone** [comment]
Why is this closed?  I just installed wharfee and see this warning:
```
> wharfee 
${VIRTUALENV}/lib/python2.7/site-packages/wharfee/main.py:325: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.command()
Version: 0.6.8
Home: http://wharfee.com
```

**Comment by j-bennet** [comment]
Because this was fixed in master:

https://github.com/j-bennet/wharfee/commit/1dead49d1a761d4ffeb9ead681fa9fd040d5887d

I'm going to release an update in a week or two. Until then, wharfee can be installed from master:

```
pip install git+https://github.com/j-bennet/wharfee.git
```

**Comment by kevinastone** [comment]
:+1:
