### ISSUE TITLE
Legal request - Change domain name to drop Docker

### ISSUE THREAD

**Issue by cjpalermo** [j-bennet/wharfee#89]
Please change the domain name "dockercli.com" to something that does not include Docker as the first term. Docker is a registered trademark of Docker, Inc. of San Francisco, California, which does not permit others to use the trademark in a domain name as the first term. We make this requirement to protect the public from confusion about whether the domain is sponsored, licensed, or associated with Docker, Inc. We regret that the difficult state of US trademark law requires us to pursue uses of this type. Best wishes for success.

Christopher J. Palermo
Hickman Palermo Becker Bingham LLP
San Jose, California
Attorneys for Docker, Inc.
Contact e-mail:  trademarks (at) h35g.com

**Comment by j-bennet** [comment]
I was not aware of this. I'll come up with something different.

**Comment by cjpalermo** [comment]
We appreciate your cooperation.

Chris

[HPBB_logo_for_email_sig]

Christopher J. Palermo, Partner
Hickman Palermo Becker Bingham LLP
1 Almaden Boulevard – Floor 12
San Jose, CA  95113  USA
T 001.408.414.1202  |  F 001.408.414.1076
www.hickmanpalermo.com<http://www.hickmanpalermo.com>

**Comment by j-bennet** [comment]
Changed domain name.

**Comment by cjpalermo** [comment]
We appreciate this step but continued use of the name “dockercli” for the code is not acceptable. Docker offers a code product called Docker CLI. You’ll have to pick something that does not use Docker as the first term.

Christopher J. Palermo

**Comment by j-bennet** [comment]
Name changed.

**Comment by kordless** [comment]
@cjpalermo: the original request you made was to change the *domain name*, not the repository name. 

When @j-bennet complied, you came back with a *new* request to change the repository name, but didn't back it up with a reason why it should be changed. In [another repository](https://github.com/codyd51/Docker/issues/3) you have requested the name to be changed, citing the reason as "the law requires Docker to actively contact others who are using similar names in the software field".

To make matters even more confusing, I'll point to [your correspondence](https://github.com/chuckbutler/docker-charm/issues/63) with @chuckbutler which seems to indicate the use of the name was OK, but the whale logo wasn't. For reference, that repo is named "docker-charm". In [another example](https://github.com/codyd51/Docker/issues/3), the use of just "docker" seems to be inappropriate, even for what appears to be self-labeled as a 'tweak' to the Dock in OSX.

Perhaps someone from Docker should go into some detail about what the rest of the ecosystem can expect from the legal department at Docker moving forward regarding naming schemes. For example, I would like to know if we are allowed to use repos named 'docker-<whatever>' if the project uses Docker in an integrated way, such as @chuckbutler's [repo which deploys Docker using Juju](https://github.com/chuckbutler/docker-charm/issues/63).

Further, Docker is an Open Source project which can be forked by others. I'm now wondering if I would get a takedown request if I forked Docker into my account.

Where should we open an issue to request guidance on naming schemes and said use of the Docker repositories?

**Comment by kordless** [comment]
Little update on this. Docker has published a set of guidelines for naming things here: https://www.docker.com/trademark-guidelines.

Basically, if you create a Docker-related project on Github, the suggestions is to NOT name it anything that starts with, or contains the term "docker".

**Comment by j-bennet** [comment]
Nice investigative work, @kordless.

**Comment by kordless** [comment]
Thanks @j-bennet. I appreciate your work on this software!

FWIW, the important bit from their guideline page is: "The Docker mark is used only in a referential context or for naming Docker or to indicate compatibility, and not in a title of a program, domain name, website, product or service."

Given this fact and that trademark laws in the US are intentionally vague, with 'confusing' being discretional, I think it's fair to say that people should not use the term 'docker' in a repository name. As others have pointed out on Twitter, it's a tad confusing anyways.

**Comment by cjpalermo** [comment]
@kordless ... In general Docker objects to the use of all repo names, or product names, that begin with Docker. In some cases, because of a business relationship that exists between Docker and a code author and/or his/her organization, we depart from that policy and grant permission or a license. Or, sometimes we are given partial information and make one request, then learn more and make a renewed or different request. So, as to @chuckbutler, all I can tell you is that there are business considerations in the background that applied to his project, but not to this one. If you believe there is a good reason that you should be able to use "docker" or "Docker" in the first part of a product name or repo name, you can certainly inform me and I can see if the product marketing group in Docker agrees that it is a permissible use.
